
import 'package:flutter/rendering.dart';

const DEFAULT_PADDING = 16.0;
const DEFAULT_MAX_PADDING = 32.0;
const DEFAULT_MIN_PADDING = 8.0;

const DEFAULT_BUTTON_PADDING = 16.0;
const DEFAULT_BORDER_RADIUS = 10.0;
const DEFAULT_THEME_CARD_RADIUS = 16.0;
const DEFAULT_ELEVATION = 8.0;
const DEFAULT_MIN_ELEVATION = 4.0;
const DEFAULT_Max_ELEVATION = 10.0;


//radius
const MIN_RADIUS = 4.0;


const TITLE_FONT_SIZE = 18.0;
const SUB_TITLE_FONT_SIZE = 17.0;
const TEXT_FONT_SIZE = 14.0;
const TEXT_LARGE_FONT_SIZE = 16.0;
const BUTTON_TEXT_LARGE_FONT_SIZE = 20.0;


const ZERO = 0.0;

//textField
const HEADER_CONTENT_PADDING = 16.0;
const DEFAULT_SPACING = 16.0;
const DEFAULT_SPACING_MIN = 8.0;
const DEFAULT_SPACING_MAX = 24.0;
const MIN_LINES=1;

const FLAG_RADIUS_MIN=15.0;
const FLAG_RADIUS_MAX=20.0;


//textField
const TEXT_FIELD_CONTENT_PADDING = 20.0;
const TEXT_FIELD_CONTENT_PADDING_MIN = 14.0;

//Splash Page dimensions
const SPLASH_LOGO_HEIGHT = 200.0;
const SPLASH_LOGO_WIDTH = 200.0;


//Login Page dimensions
const LOGIN_LOGO_HEIGHT = 80.0;
const LOGIN_LOGO_WIDTH = 80.0;


//AppBar
const APP_BAR_LEADING_WIDTH = 40.0;

//elevation
const MIN_ELEVATION = 1.0;



